namespace: \App\Controllers
routes:
  -
    method: GET
    pattern: /
    controller: PostsController@getPosts
  -
    method: GET
    pattern: /posts(/\d+)?
    controller: PostsController@getPosts
  -
    method: POST
    pattern: /posts/
    controller: PostsController@getPostsFromPagination
  -
    method: GET
    pattern: /post/(\d+)
    controller: PostController@getPost
  -
    method: POST
    pattern: /post/(\d+)
    controller: CommentController@addComment
  -
    method: GET
    pattern: /login
    controller: Auth\LoginFormController@loginForm
  -
    method: POST
    pattern: /login
    controller: Auth\LoginSubmitController@loginSubmit
  -
    method: GET
    pattern: /logout
    controller: Auth\LogoutController@logout
  -
    method: GET
    pattern: /signup
    controller: Auth\SignupFormController@signupForm
  -
    method: POST
    pattern: /signup
    controller: Auth\SignupSubmitController@signupSubmit
middlewares:
  -
    method: GET|POST
    pattern: /(login|signup)
    callback: checkIfLoggedIn