namespace: \App\Controllers
404: PageNotFoundController@notFound
routes:
  -
    method: GET
    pattern: /
    controller: PostsController@getPosts
  -
    method: GET
    pattern: /posts(/\d+)?
    controller: PostsController@getPosts
  -
    method: POST
    pattern: /posts/
    controller: PostsController@getPostsFromPagination
  -
    method: GET
    pattern: /post/(\d+)
    controller: PostController@getPost
  -
    method: POST
    pattern: /post/(\d+)
    controller: CommentController@addComment
  -
    method: GET
    pattern: /login
    controller: Auth\LoginFormController@loginForm
  -
    method: POST
    pattern: /login
    controller: Auth\LoginSubmitController@loginSubmit
  -
    method: GET
    pattern: /logout
    controller: Auth\LogoutController@logout
  -
    method: GET
    pattern: /signup
    controller: Auth\SignupFormController@signupForm
  -
    method: POST
    pattern: /signup
    controller: Auth\SignupSubmitController@signupSubmit
  -
    method: GET
    pattern: /admin
    controller: Admin\AdminDashboardController@dashboard
  -
    method: GET
    pattern: /admin/users
    controller: Admin\AdminUsersListController@usersList
  -
    method: POST
    pattern: /admin/users/update
    controller: Admin\AdminUpdateUserController@updateUserRole
  -
    method: POST
    pattern: /admin/users/delete
    controller: Admin\AdminDeleteUserController@deleteUser
middlewares:
  -
    method: GET|POST
    pattern: /(login|signup)
    callback: checkIfLoggedIn
  -
    method: GET|POST
    pattern: /(admin|admin/.*)
    callback: checkIfAdmin